version: '3.8'

services:
  app:
    image: python:3.10
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    command: >
      sh -c "
      pip install -r requirements.txt &&
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    depends_on:
      - db
    
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data: