version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    image: python:3.10
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    command: >
      sh -c "
      pip install -r requirements.txt &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    depends_on:
      - db
