"""added a relationship column with question

Revision ID: 0baaaa017e6d
Revises: 714a4cf13575
Create Date: 2024-07-14 06:43:46.262581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0baaaa017e6d'
down_revision: Union[str, None] = '714a4cf13575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'question_id')
    # ### end Alembic commands ###
