"""Added index to db

Revision ID: e197f6bf2686
Revises: ccdd8b01dd0c
Create Date: 2024-07-17 16:49:26.018790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e197f6bf2686'
down_revision: Union[str, None] = 'ccdd8b01dd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'tagName',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.create_index(op.f('ix_tags_tagName'), 'tags', ['tagName'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_tagName'), table_name='tags')
    op.alter_column('tags', 'tagName',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
